config/routes.rb
Rails.application.routes.draw do
  #get 'users/show'
  #get 'dictionaries/index'
  devise_for :users
  root to: "dictionaries#index"
  resources :dictionaries do
    resources :contents, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, category: '--' },
    { id: 2, category: '英語' },
    { id: 3, category: '外国語' },
    { id: 4, category: '国語・古典' },
    { id: 5, category: '数学' },
    { id: 6, category: '理科・化学・物理' },
    { id: 7, category: '社会・歴史・地理' },
    { id: 8, category: '中学校' },
    { id: 9, category: '高校' },
    { id: 10, category: '大学・専門学校' },
    { id: 11, category: '資格' },
    { id: 12, category: 'SPI' },
    { id: 13, category: '独学' },
    { id: 14, category: '専門分野' },
    { id: 15, category: '図鑑' },
    { id: 16, category: '趣味' },
    { id: 17, category: 'その他' },
]
  include ActiveHash::Associations
  has_many :dictionaries
end
  

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :dictionary
  with_options presence: true do
    validates :phrase, length: { maximum: 40 }
    validates :content_mean, length: { maximum: 1000 }
    validates :phrase_reference
  end

end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
  belongs_to :user
  has_many :contents, foreign_key: :dictionary_id, dependent: :destroy
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  with_options presence: true do
    validates :name, length: { maximum: 40 }
    validates :info, length: { maximum: 500 }
  end

  validates :category_id, numericality: { other_than: 1 } 

  #def self.search(search) #self.でクラスメソッドとしている
    #if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      #Content.where(['phrase LIKE ?', "%#{search}%"])
    #else
      #Content.all #全て表示。
    #end
  #end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :dictionary
  validates_uniqueness_of :dictionary_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  has_many :dictionaries
  has_many :likes
  has_many :liked_dictionaries, through: :likes, source: :dictionary
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
  validates :nickname, presence: true 
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }

  def liked_by?(dictionary)
    self.likes.exists?(dictionary_id: dictionary.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index, :show]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_dictionary, except: [:show, :destroy]
  def new
    @content = Content.new
    #@dictionary = Dictionary.find(params[:dictionary_id])
  end

  def create
    #@dictionary = Dictionary.find(params[:dictionary_id])
    @content = Content.new(content_params)    
    if @content.save
      redirect_to dictionary_path(@dictionary)
    else
      render :new
    end
  end

  def show
    @content = Content.find(params[:id])
    @dictionary = @content.dictionary
    #@search = Content.ransack(params[:q])
    #@contents = @search.result
  end
  

  def edit
    #@dictionary = Dictionary.find(params[:dictionary_id])
    @content = Content.find(params[:id])
    #if current_user.id != @dictionary.user_id 
      #redirect_to root_path
    #end
  end

  def update
    #@dictionary = Dictionary.find(params[:dictionary_id])
    @content = Content.find(params[:id])
    if @content.update(content_params)
      redirect_to dictionary_content_path(@dictionary, @content)
    else
      rencer :edit
    end
  end

  def destroy
    @dictionary = Dictionary.find(params[:id])
    @content = Content.find(params[:id])
    if current_user.id == @dictionary.user_id
      @content.destroy
      redirect_to dictionary_path(@dictionary)
    end
  end

  private

  def content_params
    params.require(:content).permit(:phrase, :content_mean, :phrase_reference).merge(dictionary_id: @dictionary.id)
  end

  def set_dictionary
    @dictionary = Dictionary.find(params[:dictionary_id])
  end
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  before_action :dictionary_substitution, except: [:index, :new, :create, :search]

  def index
    @search = Dictionary.ransack(params[:q])
    @dictionaries = @search.result
    #category_id = params[:q][:category_id_eq]
    #@category = Category.find_by(id: category_id)

  end

  def new
    @dictionary = Dictionary.new
  end

  def create
    @dictionary = Dictionary.new(dictionary_params)
    if @dictionary.save
      redirect_to dictionary_path(@dictionary)
    else
      render :new
    end
  end

  def show
    @contents = @dictionary.contents
    @likes = Like.where(dictionary_id: @dictionary.id)
    if user_signed_in?
      @like = Like.find_by(user_id: current_user.id, dictionary_id: @dictionary.id)
    end
  end

  def edit
    if current_user.id != @dictionary.user_id
      redirect_to root_path
    end
  end

  def update
    if @dictionary.update(dictionary_params)
      redirect_to dictionary_path(@dictionary)
    else
      render :edit
    end
  end

  def destroy
    @contents = @dictionary.contents
    if current_user.id == @dictionary.user_id
      @contents.destroy
      @dictionary.destroy
      redirect_to user_path(current_user)
    else
      redirect_to dictionary_path(@dictionary)
    end
  end

  def search
    @dictionaries = @q.result(distinct: true)
  end

  private

  def dictionary_params
    params.require(:dictionary).permit(:name,:info,:category_id).merge(user_id: current_user.id)
  end

  def dictionary_substitution
    @dictionary = Dictionary.find(params[:id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(dictionary_id: params[:dictionary_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @dictionary = Dictionary.find(params[:dictionary_id])
    @like = Like.find_by(dictionary_id: params[:dictionary_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path) 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @dictionaries = @user.dictionaries
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/contents/edit.html.erb
<%= render "shared/second-header"%>
<div class="dictionaries-new-page">
  <div class="dictionary-main">
    <h2 class="dictionary-title">語句を編集しよう！</h2>
    <%= form_with(model: [@dictionary, @content], local: true) do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="new-dictionaries">
      <div class="weight-bold-text">
        語句
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :phrase, class:"dictionaries-text", id:"content-phrase", placeholder:"辞書に追加したい語句（必須 40文字まで)", maxlength:"40" %>
      <div class="weight-bold-text">
        意味・説明
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :content_mean, class:"dictionaries-text", id:"content-mean", placeholder:"意味・説明（必須 1,000文字まで）", rows: "7", cols: "75", maxlength:"1000" %>
      <div class="weight-bold-text">
        参照したサイトURl、参考書、その他メモ等
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :phrase_reference, class:"dictionaries-text", id:"content-phrase-reference", placeholder:"内容の説明（必須 1,000文字まで）", rows: "7", cols: "75", maxlength:"1000" %>
    </div>
    <div class="dictionary-btn-contents">
      <%= f.submit "編集" , class:"content-edit-btn" %>
    </div>
    <% end %>
  </div>
</div>

app/views/contents/new.html.erb
<%= render "shared/second-header"%>
<div class="dictionaries-new-page">
  <div class="dictionary-main">
    <h2 class="dictionary-title">語句を追加しよう！</h2>
    <%= form_with model: @content, url: dictionary_contents_path, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="new-dictionaries">
      <div class="weight-bold-text">
        追加したい語句
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :phrase, class:"dictionaries-text", id:"content-phrase", placeholder:"辞書に追加したい語句（必須 40文字まで)", maxlength:"40" %>
      <div class="weight-bold-text">
        辞書内容の説明
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :content_mean, class:"dictionaries-text", id:"content-mean", placeholder:"意味・説明（必須 1,000文字まで）", rows: "7", cols: "75", maxlength:"1000" %>
      <div class="weight-bold-text">
        参照したサイトURl、参考書、その他メモ等
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :phrase_reference, class:"dictionaries-text", id:"content-phrase-reference", placeholder:"内容の説明（必須 1,000文字まで）", rows: "7", cols: "75", maxlength:"1000" %>
    </div>
    <div class="dictionary-edit-btn">
      <% if current_user == @dictionary.user %>
        <%= f.submit "追加する" , class:"content-edit-btn" %>
      <% end %>
      <%= button_to "戻る", dictionary_path(@dictionary), class: "back--btn" %>
      <%#= link_to " 戻る ", dictionary_path(@dictionary), class:"content-back--btn" %>
    </div>
    <% end %>
  </div>
</div>

app/views/contents/show.html.erb
<%= render "shared/second-header"%>
<div class="dictionary-show-page">
  <div class="content-show">
    <h2 class="contents-list-main">
      <%= @content.phrase %>
    </h2>
    <div class="contents-list">
      <h3 class="content-mean">
        <p>『 意味・説明 』</p>
        <%= @content.content_mean %>
      </h3>
      <h5 class="phrase_reference">
        <p>『 参照したサイトURl、参考書、その他メモ等 』</p>
        <%= @content.phrase_reference %>
      </h5>
    </div>
  </div>
  <div class="dictionary-edit-btn">
    <% if current_user.id == @dictionary.user_id %>
      <%= link_to " 編集する ", edit_dictionary_content_path(@dictionary.id, @content), class:"content-edit-btn" %>
      <%= link_to " 削除する ", dictionary_content_path(@dictionary, @content), method: :delete, class:"destroy-btn" %>
    <% end %>
    <%= link_to " 戻る ", dictionary_path(@dictionary), class:"back--btn" %>
  </div> 
</div>

app/views/dictionaries/edit.html.erb
<%= render "shared/second-header"%>
<div class="dictionaries-new-page">
  <div class="dictionary-main">
    <h2 class="dictionary-title">辞書を編集しよう！</h2>
    <%= form_with model: @dictionary, local: true do |f| %>
    
    <%= render 'shared/error_messages', model: f.object %>

    <div class="new-dictionaries">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"dictionaries-text", id:"dictionary-name", placeholder:"辞書のタイトル名（必須 40文字まで)", maxlength:"40" %>
      <div class="weight-bold-text">
        内容の説明
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :info, class:"dictionary-text", id:"dictionary-info", placeholder:"内容の説明（必須 100文字まで）（学科、試験名、資格名、用途）例）2021年ITスキル検定1級受験用に作成しました。追記要望や内容相違点についてお気づきの点がありましたら、是非コメントをお願いいたします。", rows: "7", cols: "75", maxlength:"100" %>
    </div>
    <div class="dictionaries-detail">
        <div class="form">
          <div class="weight-bold-text">
            カテゴリー
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:category_id, Category.all, :id, :category, {}, {class:"select-box", id:"dictionary-category"}) %>
        </div>
    </div>
      <% if user_signed_in? %>
        <div class="dictionary-edt-btn">
          <%= f.submit "変更する",class:"dictionary--btn" %>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>  

app/views/dictionaries/index.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class='title-contents'>
    <h2 class='top-page-title'>
      オリジナルの辞書を作成して出版しよう！
    </h2>
    <p class='top-page-text'>
      自分好みのワードを追加していこう！
    </p>
    <p class='top-page-text'>
      いいねが増えると出版できる！
    </p>
  </div>
  <div class='main-image'>
      <%= image_tag "ELL75_yousyohondana20120620_TP_V.jpg", class:"main-pict" %>
      <%= image_tag "people-4050698_1920.jpg", class:"main-pict" %>
  </div>
  <div class='dictionary-contents'>
    <h2 class='title'>投稿辞書一覧</h2>
    <%#辞書検索%>
    <%= search_form_for @search do |f| %>
      <%= f.label :name_cont, "辞書の名前" %>
      <%= f.search_field :name_cont %>
      <%#div class="search_category" >
        <%= f.label "カテゴリー" %>        
        <%#= f.collection_select(:category_id_eq, Category.all, :id, :category, {}, {class:"search-select-box", id:"dictionary-category"}) %>
      <%#/div#%>
      <%= f.submit class:"dictionary-search-btn" %>
    <% end %>
    <ul class='dictionary-lists'>
      <% if @dictionaries.present? %>
        <% @dictionaries.each do |dictionary| %> 
          <li class='list'>
            <%= link_to "#{dictionary.name}", dictionary_path(dictionary) %>
            <div class='dictionary-category'>
                <span><%= dictionary.category.category %></span>
                <div class='heart-btn'>
                  <%= image_tag "heart.png", class:"heart-icon" %>
                  <span class='heart-count'><%= dictionary.likes.count %></span>
                </div>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div class="create-new-dictionary">
    <%= link_to "create new", new_dictionary_path,  class: 'new-create-btn' %>
  </div>
</div>

app/views/dictionaries/new.html.erb
<%= render "shared/second-header"%>
<div class="dictionaries-new-page">
  <div class="dictionary-main">
    <h2 class="dictionary-title">新しく辞書を作成しよう！</h2>
    <%= form_with model: @dictionary, url: dictionaries_path, local: true do |f| %>
    
    <%= render 'shared/error_messages', model: f.object %>
    
    <div class="new-dictionaries">
      <div class="weight-bold-text">
        辞書の名前・タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"dictionaries-text", id:"dictionary-name", placeholder:"辞書のタイトル名（必須 40文字まで)", maxlength:"40" %>
      <div class="weight-bold-text">
        辞書内容の説明
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :info, class:"dictionaries-text", id:"dictionary-info", placeholder:"内容の説明（必須 500文字まで）（学科、試験名、資格名、用途）例）2021年ITスキル検定1級受験用に作成しました。追記要望や内容相違点についてお気づきの点がありましたら、是非コメントをお願いいたします。", rows: "7", cols: "75", maxlength:"500" %>
    </div>
    <div class="dictionaries-detail">
        <div class="form">
          <div class="weight-bold-text">
            カテゴリー
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:category_id, Category.all, :id, :category, {}, {class:"select-box", id:"dictionary-category"}) %>
        </div>
    </div>
    <div class="dictionary-btn-contents">
      <%= f.submit "新規作成" ,class:"dictionary--btn" %>
    </div>
    <% end %>
  </div>
</div>

app/views/dictionaries/show.html.erb
<%= render "shared/second-header"%>

<div class="dictionary-show-page">
  <div class="dictionary-show">
    <h2 class="show-name">
      <%= @dictionary.name %>
      「　作成者：　<%= link_to @dictionary.user.nickname, user_path(@dictionary.user.id) %>　」
    </h2>
    <h3>
      <%= @dictionary.info %>
    </h3>
  <%#語句検索#%>
    <%#= search_form_for @search do |f| %>
      <%#= f.search_field :@content.phrase_cont %>
      <%#= f.submit "検索" %>
    <%# end %>
    <div class="contents-list-main">
      <ul class="contents-list">
        <% if @dictionary.contents.present? %>
          <% @dictionary.contents.each do |content| %> 
            <li class='contents-list-text'>
              <%= link_to dictionary_content_path(@dictionary, content) do %>
                <%= content.phrase %>
              <% end %>
              <p><%= content.content_mean %></p>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div> 
    

    <h2 class="good-count">
      いいねしたユーザー数 <%= image_tag "heart.png", class:"heart-icon" %><%= @dictionary.likes.count %>
    </h2>
    <div class="dictionary-show-btn">
      <% if current_user == @dictionary.user %>
        <%= link_to " 辞書の編集 ", edit_dictionary_path(@dictionary), class:"dictionary--btn" %>
        <%= link_to " 語句の追加 ", new_dictionary_content_path(@dictionary.id), class:"content-edit-btn" %>
        <%= link_to "　削除　", dictionary_path(@dictionary), method: :delete, class:"destroy-btn" %>
        <% if @dictionary.likes.count >= 1 %>
          <%= link_to "出版する", "#", class:"edition-btn" %>
        <% end %>
        <%= link_to " 戻る ", user_path(@dictionary), class:"back--btn" %>
      <% else %>
        <div class="login-show-btn">
          <% if user_signed_in? %>
            <% if current_user.liked_by?(@dictionary) %>
              <%= button_to "いいねを取消す", dictionary_like_path(@dictionary.id, @like.id), method: :delete, class:"good-btn" %>
            <% else %>
              <%= button_to "いいね", dictionary_likes_path(@dictionary.id), class:"good-btn" %>
            <% end %>
          <% end %>
          <%= link_to :back do %>
          <button class="back--btn">戻る</button>
          <% end %>
        </div> 
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
    <title>Myejition2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
       <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header>
  <div class="header-title">
    <%= link_to "My Ejition", "/", class:"header-title-text" %>
  </div>
  <div class="header-btn">
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, user_path(current_user), class: "user-nickname" %></li> 
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li> 
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-header.html.erb
<header>
  <div class="header-title">
    <%= link_to "My Ejition", "/", class:"header-title-text" %>
  </div>
</header>

app/views/users/show.html.erb
<%= render "shared/second-header"%>
<div class="dictionaries-new-page">
  <div class="dictionary-main">
    <h2 class="dictionary-title"><%= "#{@user.nickname}" %>さんのマイページ</h2>
  </div>
  <ul class='dictionary-lists'>
      <% if @dictionaries.present? %>
        <% @dictionaries.each do |dictionary| %> 
          <li class='list'>
            <%= link_to "#{dictionary.name}", dictionary_path(dictionary) %>
            <div class='dictionary-category'>
                <span><%= dictionary.category.category %></span>
                <div class='heart-btn'>
                  <%= image_tag "heart.png", class:"heart-icon" %>
                  <span class='heart-count'>0</span>
                </div>
            </div>
          </li>
        <% end %>
      <% end %>
  </ul>
  <h2 class="good-title">いいねしている辞書</h2>
    <ul class="dictionary-good-lists">
      <% @user.liked_dictionaries.each do |dictionary| %>
        <li class="good-list">
          <%= link_to "#{dictionary.name}", dictionary_path(dictionary) %>
          <div class='dictionary-category'>
                <span><%= dictionary.category.category %></span>
                <div class='heart-btn'>
                  <%= image_tag "heart.png", class:"heart-icon" %>
                  <span class='heart-count'>0</span>
                </div>
            </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>